### ISSUE TITLE
DLL missing

### ISSUE THREAD

**Issue by sznadas** [andymasteroffish/tcg_proxy_gen#2]
On stock windows 10 a dll is missing sometimes. That can be fixed by installing the x86 version of Microsoft Visual C++ 2015 Redistributable at e.g. https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by sznadas** [comment]
Maybe add this info to the readme and the install guide on the homepage.

**Comment by andymasteroffish** [comment]
Thanks for pointing this out! I haven't touched this project in ages, but adding something to the readme should be a pretty easy thing to do.

**Comment by andymasteroffish** [comment]
Was this missing in order to compile the code, or was it missed when you went to run the executable from Itch?

**Comment by sznadas** [comment]
I was required to run it. I have not tried compiling it.

**Comment by andymasteroffish** [comment]
OK cool. Thanks for the heads up!

**Comment by sznadas** [comment]
Thanks for the tool btw. :)

**Comment by andymasteroffish** [comment]
I'm glad you dig it! If you don't mind sharing, what game are you using it for?

**Comment by sznadas** [comment]
Hatalom Kartyai, a Hungarian tcg.

**Comment by andymasteroffish** [comment]
Itch page and windows readme have been updated! Thanks for pointing this out.

Cool about Hatalom Kartyai! I'd never heard of it before!
